services:
  nginx:
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    image: nginx:inception
    container_name: nginx
    volumes:
      - wordpress-data:/var/www/html:ro
    networks:
      - inception
    ports:
      - "443:443"
    environment:
      - CERTS_PATH
      - DOMAIN_NAME
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy
  wordpress:
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    image: wordpress:inception
    container_name: wordpress
    healthcheck:
      test: ["CMD-SHELL", "php-fpm83 -t || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes: 
      - wordpress-data:/var/www/html
    networks:
      - inception
    environment:
      - DOMAIN_NAME
      - WP_TITLE
      - WP_ADMIN_EMAIL
      - WP_ADMIN_USER
      - WP_USER
      - WP_USER_EMAIL
      - DB_NAME
      - DB_USER
      - DB_HOST
    secrets:
      - wp_admin_password
      - wp_user_password
      - db_password
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_healthy
  mariadb:
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    image: mariadb:inception
    container_name: mariadb
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -u ${DB_USER} -p$$(cat /run/secrets/db_password) --socket=/var/run/mysqld/mysqld.sock --silent || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
    environment:
      - DB_NAME
      - DB_USER
    secrets:
      - db_password
      - db_root_password
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
  redis:
    build:
      context: ./requirements/bonus/redis
      dockerfile: Dockerfile
    image: redis:inception
    container_name: redis
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD","redis-cli",ping]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s
  adminer:
    build:
      context: ./requirements/bonus/adminer
      dockerfile: Dockerfile
    image: adminer:inception
    container_name: adminer
    restart: always
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
  ftp:
    build:
      context: ./requirements/bonus/ftp
      dockerfile: Dockerfile
    image: ftp:inception
    container_name: ftp
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    environment:
      - FTP_USER
    secrets:
      - ftp_pass
    volumes:
      - wordpress-data:/var/www/html
  portainer:
    build:
      context: ./requirements/bonus/portainer
      dockerfile: Dockerfile
    image: portainer:inception
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
  
  static-site:
    build:
      context: ./requirements/bonus/static-site
      dockerfile: Dockerfile
    image: static-site:inception
    container_name: static-site
    restart: unless-stopped
    networks:
      - inception
volumes:
    mariadb-data:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: /home/sessarhi/data/mariadb
    wordpress-data:
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/sessarhi/data/wordpress
    portainer-data:
      driver: local
      driver_opts:
          type: none
          o: bind
          device: /home/sessarhi/data/portainer

networks:
  inception:
    name: inception
    driver: bridge
secrets:
  db_password:
    file: ../secrets/db_password.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
     file: ../secrets/wp_user_password.txt
  ftp_pass:
    file: ../secrets/ftp_pass.txt
